name: hispace_mobile_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.0+1-alpha

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cafe_api:
    path: packages/cafe/cafe_api
  cafe_repository:
    path: packages/cafe/cafe_repository
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.5
  formz: ^0.6.0
  google_fonts: ^4.0.4
  http_cafe_api:
    path: packages/cafe/http_cafe_api
  hydrated_bloc: ^9.1.1
  json_annotation: ^4.8.1
  local_data:
    path: packages/local_data
  meta: ^1.9.1
  page_transition: ^2.0.9
  path_provider: ^2.0.15
  smooth_page_indicator: ^1.1.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/icons/
    - assets/images/
