name: http_cafe_api
description: A new Flutter package project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cafe_api:
    path: ../cafe_api
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  http: ^1.0.0
  local_data:
    path: ../../local_data
  mockito: ^5.4.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
