name: hiSpace App Release

on:
    pull_request:
        branches:
            - master
jobs:
    flutter_test:
        name: Run flutter test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v1
              with:
                  java-version: '12.x'
            - uses: subosito/flutter-action@v1
              with:
                  channel: 'stable'
            - run: flutter pub get
            - run: flutter analyze
            - run: flutter test packages/cafe/http_cafe_api/ 
            - run: flutter test packages/geolocation/openstreetmap_api
            - run: flutter test packages/authentication_repository
            - run: flutter test packages/user_repository
            
    android_relase:
        name: Build Flutter (Android)
        needs: [flutter_test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
            - run: flutter --version
            - run: flutter pub get
            - run: flutter build apk --release --split-per-abi
            - run: flutter build appbundle
            - name: Create a Release in GitHub
              uses: ncipollo/release-action@v1
              with:
                artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
                token: ${{ secrets.RELEASE_TOKEN }}
                tag: v0.0.${{ github.run_number }}
                commit: ${{ github.sha }}
